config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {sessions: "sessions"}

  # About
  get 'quem-somos' => 'about#index', as: :about

  # Contact
  get 'contato' => 'contacts#index', as: :contacts
  post 'contato' => 'contacts#create', as: :create_contact


  root 'feeder#index'
  get 'dispositivos' => 'devices#index', as: :list_devices


  get 'home' => 'home#index', as: :home

  #avaliacao
  get 'avaliacao/dispositivo/:id' => 'question#evaluation', as: :evaluations
  post 'avaliacao/dispositivo/:id' => 'question#create_evaluation'
  get 'minhasavaliacoes' => 'evaluations#index', as: :list_evaluations

  # reports
  get 'dispositivos/selecao' => 'reports#index', as: :device_seletion
  get 'relatorios/avaliacoes' => 'reports#evaluation', as: :report_evaluation
  get 'dispositivo/relatorio/:id' => 'reports#show', as: :report

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :access, :rails_admin
      can :manage, :all   
    else
      can :read, :all
    end
  end
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, :content, presence: true
  has_many :about_images, dependent: :destroy

  accepts_nested_attributes_for :about_images, allow_destroy: true

  def images
    about_images
  end
end

app/models/about_image.rb
class AboutImage < ApplicationRecord
  mount_uploader :image, AboutUploader

  validates :image, presence: true

  belongs_to :about

  def show
    image
  end
end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  enum type_alternative:  %w(accessibility usability)
  has_and_belongs_to_many :questions

  validates :description, :weight, presence: true

  def name
    description
  end


end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :description, presence: true
  has_many :questions

  def name
      description
  end

  def self.include_category
    category = Category.order(:id)
    category.includes(:questions).order(:id)
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :phone, :message, :subject, presence: true
end

app/models/device.rb
class Device < ActiveRecord::Base
  include SearchCop
  mount_uploader :phone_img, CellImageUploader

  belongs_to :mark
  has_many :evaluations
  validates :phone_img, :model_device, :processor, :os, :size_device, :type_device, :mark, presence:true

  # Implementation search with gem searchcop
  search_scope :search do
    attributes :model_device, :processor, :os, :type_device
  end


  def cont_eval
    evaluations.count
  end

  # def self.search(search)
  #   where("model_device like ?", "%#{search}%")
  # end


  def percent_of_evaluation(eval_spec)
    percent = 0
    percent = (eval_spec * 100 / cont_eval)
    percent > 0 ? percent.to_s << "%" :percent
  end


end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  enum type_diagnostic:  %w(accessibility usability)


  validates :description, :score, presence: true


  def self.result (s, t)
    result = where('score <= ?', s).where('type_diagnostic = ?', t).first
    result.try(:description)
  end

  def self.count (s, t)
    result = where('score <= ?', s).where('type_diagnostic = ?', t).count
    result.try(:description)
  end

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :device
  belongs_to :user
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  has_many :devices
  validates :name, presence: true

  end

app/models/question.rb
class Question < ActiveRecord::Base

  enum type_question:  %w(accessibility usability)

  belongs_to :category
  belongs_to :quiz

  has_and_belongs_to_many :alternatives

  def name
    enunciation
  end

  def self.include_category
    category = Category.order(:id)
    category.includes(:questions).order(:id)
  end
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  has_many :questions
end

app/models/slide.rb
class Slide < ApplicationRecord
  mount_uploader :image, SlideUploader
  validates :title, :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :evaluations

end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/report_helper.rb
module ReportHelper

  def search_score_diagnostic
    @sim = Diagnostic.find_by(name: 'Sim')
  end



  def search_score_diagnostic_acessibilidade
    @sim = Diagnostic.find_by(name: 'Sim')
    @nao = Diagnostic.find_by(name: 'Não')
  end


  def eval_spec(device, dg)
   @evals_yes =  Evaluation.where("device_id = ?", device).where("score_acessibilidade = ? ", dg.first.score).count
   @evals_no =  Evaluation.where("device_id = ?", device).where("score_acessibilidade = ? ", dg.last.score).count

  end



  def percent_of_votes
    percent = 0
    percent = (votes * 100 / poll_question.votes) if votes.size > 0 && poll_question.votes > 0
    percent > 0 ? percent.to_s << "%" :percent
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/includes/_head_devise.erb
<head>
	<%= favicon_link_tag 'admin/icon.png' %>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Área Administrativa - Lupa</title>

	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag :modernizr %>
</head>

app/views/layouts/includes/_menu.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="/home"><i class="fa fa-search span-menu"></i>LUPA</a>
    </li>
    <li>
      <a href="/dispositivos"><i id="" class="fa fa-desktop fa-lg  span-menu"></i>Dispositivos</a>
    </li>
    <li>
      <a href="<%= list_evaluations_path%>"><i class="fa fa-pencil fa-lg span-menu" ></i>Minhas Avaliações</a
    </li>
    <li>
      <a href="<%= device_seletion_path%>"><i class="fa fa-book fa-lg span-menu"></i>Relatório</a>
    </li>
    <li>
    <%= link_to  destroy_user_session_path, method: :delete do%>
      <i class="fa fa-sign-out fa-lg span-menu"></i>Sair
    <%end%>
    </li>
  </ul>
</div>

app/views/layouts/includes/_slide.html.erb
<div class="slide owl-carousel">
  <% slides.each do |slide| %>
    <figure class="slide__figure">
      <%= image_tag slide.image, class: 'slide__image' %>
    </figure>
  <% end %>
</div>

app/views/layouts/includes/_social.html.erb
<div class="social">
  <span class="social__caption">Compartilhar</span>

  <a class="icon__btn icon__btn--tiny" target="_blank" href="http://www.facebook.com/share.php?u=<%= request.url %>&title=<%= @page_title %>">
    <span class="ion-social-facebook"></span>
  </a>

  <a class="icon__btn icon__btn--tiny" target="_blank" href="http://twitter.com/intent/tweet?status=<%= @page_title %> - <%= request.url %>">
    <span class="ion-social-twitter"></span>
  </a>

  <a class="icon__btn icon__btn--tiny" target="_blank" href="https://plus.google.com/share?url=<%= request.url %>">
    <span class="ion-social-googleplus-outline"></span>
  </a>

  <a class="icon__btn icon__btn--tiny" href="whatsapp://send?text=<%= @page_title %> - <%= request.url %>" data-action="share/whatsapp/share">
    <span class="ion-social-whatsapp-outline"></span>
  </a>
</div>

app/views/simple_captcha/_simple_captcha.erb
<div class="captcha">
  <div class="captcha__field">
    <label class="form__label" for="captcha">Confirmação</label>
    <%= simple_captcha_options[:field] %>
  </div>

  <div class="captcha__content">
    <div class="captcha__btn">
      <%= simple_captcha_options[:refresh_button] %>
    </div>

    <div class="captcha__figure">
      <%= simple_captcha_options[:image] %>
    </div>
  </div>
</div>