config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {sessions: "sessions"}

  # About
  get 'quem-somos' => 'about#index', as: :about

  # Contact
  get 'contato' => 'contacts#index', as: :contacts
  post 'contato' => 'contacts#create', as: :create_contact


  root 'feeder#index'
  get 'dispositivos' => 'devices#index', as: :list_devices


  get 'home' => 'home#index', as: :home

  #avaliacao
  get 'avaliacao/dispositivo/:id' => 'question#evaluation', as: :evaluations
  post 'avaliacao/dispositivo/:id' => 'question#create_evaluation'
  get 'minhasavaliacoes' => 'evaluations#index', as: :list_evaluations

  # reports
  get 'dispositivos/selecao' => 'reports#index', as: :device_seletion
  get 'relatorios/avaliacoes' => 'reports#evaluation', as: :report_evaluation
  get 'dispositivo/relatorio/:id' => 'reports#show', as: :report

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :access, :rails_admin
      can :manage, :all   
    else
      can :read, :all
    end
  end
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, :content, presence: true
  has_many :about_images, dependent: :destroy

  accepts_nested_attributes_for :about_images, allow_destroy: true

  def images
    about_images
  end
end

app/models/about_image.rb
class AboutImage < ApplicationRecord
  mount_uploader :image, AboutUploader

  validates :image, presence: true

  belongs_to :about

  def show
    image
  end
end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  enum type_alternative:  %w(accessibility usability)
  has_and_belongs_to_many :questions

  validates :description, :weight, presence: true

  def name
    description
  end


end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :description, presence: true
  has_many :questions

  def name
      description
  end

  def self.include_category
    category = Category.order(:id)
    category.includes(:questions).order(:id)
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :phone, :message, :subject, presence: true
end

app/models/device.rb
class Device < ActiveRecord::Base
  include SearchCop
  mount_uploader :phone_img, CellImageUploader

  belongs_to :mark
  has_many :evaluations
  validates :phone_img, :model_device, :processor, :os, :size_device, :type_device, :mark, presence:true

  # Implementation search with gem searchcop
  search_scope :search do
    attributes :model_device, :processor, :os, :type_device
  end


  def cont_eval
    evaluations.count
  end

  # def self.search(search)
  #   where("model_device like ?", "%#{search}%")
  # end


  def percent_of_evaluation(eval_spec)
    percent = 0
    percent = (eval_spec * 100 / cont_eval)
    percent > 0 ? percent.to_s << "%" :percent
  end


end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  enum type_diagnostic:  %w(accessibility usability)


  validates :description, :score, presence: true


  def self.result (s, t)
    result = where('score <= ?', s).where('type_diagnostic = ?', t).first
    result.try(:description)
  end

  def self.count (s, t)
    result = where('score <= ?', s).where('type_diagnostic = ?', t).count
    result.try(:description)
  end

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :device
  belongs_to :user
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  has_many :devices
  validates :name, presence: true

  end

app/models/question.rb
class Question < ActiveRecord::Base

  enum type_question:  %w(accessibility usability)

  belongs_to :category
  belongs_to :quiz

  has_and_belongs_to_many :alternatives

  def name
    enunciation
  end

  def self.include_category
    category = Category.order(:id)
    category.includes(:questions).order(:id)
  end
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  has_many :questions
end

app/models/slide.rb
class Slide < ApplicationRecord
  mount_uploader :image, SlideUploader
  validates :title, :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :evaluations

end

app/controllers/band_controller.rb
class BandController < ApplicationController
  def index_band
    
  end
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/report_helper.rb
module ReportHelper

  def search_score_diagnostic
    @sim = Diagnostic.find_by(name: 'Sim')
  end



  def search_score_diagnostic_acessibilidade
    @sim = Diagnostic.find_by(name: 'Sim')
    @nao = Diagnostic.find_by(name: 'Não')
  end


  def eval_spec(device, dg)
   @evals_yes =  Evaluation.where("device_id = ?", device).where("score_acessibilidade = ? ", dg.first.score).count
   @evals_no =  Evaluation.where("device_id = ?", device).where("score_acessibilidade = ? ", dg.last.score).count

  end



  def percent_of_votes
    percent = 0
    percent = (votes * 100 / poll_question.votes) if votes.size > 0 && poll_question.votes > 0
    percent > 0 ? percent.to_s << "%" :percent
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/band/index_band.html.erb
<!DOCTYPE html>
<html lang="pt-Br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width='device-width', initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Capa</title>
</head>
<body>
  <header class="header clearfix">
    <h1 class="logo">
      <span class="fa fa-search logo__icon"></span>
      <span class="logo__text">Lupa</span>
    </h1>
    <nav class="nav">
      <ul class="ul-remove">
        <li class="li corpo"><a href="#qsomos"><span class="fa fa-child  span-nav-logo"></span>Quem Somos</a></li>
        <li class="li login"><a href="<%= rails_admin_path%>"><span class="fa fa-sign-in  span-nav-logo"></span>Sign in</a></li>
      </ul>
    </nav>
  </header>
  <section class="section__capa" >
    <h1 class="titulo-so">Lupa: Sistema de Apoio para Avaliação da Usabilidade e Acessibilidade Móvel</h1>
  </section>
  <section class="  clearfix">
    <h1 class="titulo-so">Você Sabia ?</h1>

    <div class="container clearfix">
        <article class="section__item">
          <h1 class="section__title--secondary">O que é o Lupa?</h1>
          <div class="section__text">
            <p>
              É um sistema idealizado para automatizar o processo de cadastro,
              listagem e geração de relatórios das ocorrências e desempenhos
              escolares de forma simplificada.
            </p>
          </div>
        </article>
        <article class="section__item">
          <h1 class="section__title--secondary">Nosso Objetivo</h1>
          <div class="section__text">
            <p>
              Nosso maior objetivo é proporcionar aos nossos futuros clientes
              um sistema que controle todo o processo de ocorrências e relatórios de
              desempenho escolar de forma prática e segura. Neste sentido,
              estamos trabalhando em um sistema limpo é agil, focado no usuário
              e em suas necessidades.
            </p>
          </div>
        </article>
        <article class="section__item">
          <h1 class="section__title--secondary">Público Alvo</h1>
          <div class="section__text">
            <p>
              Nosso público alvo são as instituições de ensino em seus diversos
              níveis, desde a educação básica ao ensino médio. Dentre estas diversas
              etápas, buscamos as pequenas e medias instituições que necessitam de
              um sistema com baixo custo e alto benefício.
           </p>
          </div>
        </article>
      </div>
      <div class="container_utonium">
        <%= image_tag "prof_utonium.gif", :class => "img_utonium"%>
      </div>
  </section>
  <section id="qsomos" class="section__quemsomos">
    <h1  class="section__titulo--quemsomos titulo-so">Quem somos</h1>
    <div class="container__quemsomos">
      <article class="article__quemsomos clearfix">
          <h1 class="article__titulo--quemsomos">Erick Lino Pedro</h1>
          <div class="container_img_article">
          <%= image_tag "Erick.jpg" , :class=> "img_article"%>
          </div>
          <div class="article__text">
            <p>
              é acadêmico do curso de Tecnologia em Análise e Desenvolvimento de
              Sistemas do Instituto Federal de Educação, Ciência e Tecnologia de
              Mato Grosso do Sul (IFMS), campus Nova Andradina, onde atua como
              aluno pesquisador no Núcleo Interdisciplinar de Pesquisa, Estudo e
              Desenvolvimento em Tecnologia da Informação (NIPETI). Desenvolve
              estudos na área de Engenharia de Software, atuando principalmente
               com Usabilidade de Sistemas.
          </p>
        </div>
    </article>
    <article class="article__quemsomos clearfix">
        <h1 class="article__titulo--quemsomos">Erick Lino Pedro</h1>
        <div class="container_img_article">
        <%= image_tag "Erick.jpg" , :class=> "img_article"%>
        </div>
        <div class="article__text">
          <p>
            é acadêmico do curso de Tecnologia em Análise e Desenvolvimento de
            Sistemas do Instituto Federal de Educação, Ciência e Tecnologia de
            Mato Grosso do Sul (IFMS), campus Nova Andradina, onde atua como
            aluno pesquisador no Núcleo Interdisciplinar de Pesquisa, Estudo e
            Desenvolvimento em Tecnologia da Informação (NIPETI). Desenvolve
            estudos na área de Engenharia de Software, atuando principalmente
             com Usabilidade de Sistemas.
        </p>
      </div>
  </article>
  </div>
</section>

























</body>
</html>