config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {sessions: "sessions"}

  # About
  get 'quem-somos' => 'about#index', as: :about

  # Contact
  get 'contato' => 'contacts#index', as: :contacts
  post 'contato' => 'contacts#create', as: :create_contact


  root 'feeder#index'
  get 'dispositivos' => 'devices#index', as: :list_devices


  get 'home' => 'home#index', as: :home

  #avaliacao
  get 'avaliacao/dispositivo/:id' => 'question#evaluation', as: :evaluations
  post 'avaliacao/dispositivo/:id' => 'question#create_evaluation'
  get 'minhasavaliacoes' => 'evaluations#index', as: :list_evaluations

  # reports
  get 'dispositivos/selecao' => 'reports#index', as: :device_seletion
  get 'relatorios/avaliacoes' => 'reports#evaluation', as: :report_evaluation
  get 'dispositivo/relatorio/:id' => 'reports#show', as: :report

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :access, :rails_admin
      can :manage, :all   
    else
      can :read, :all
    end
  end
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, :content, presence: true
  has_many :about_images, dependent: :destroy

  accepts_nested_attributes_for :about_images, allow_destroy: true

  def images
    about_images
  end
end

app/models/about_image.rb
class AboutImage < ApplicationRecord
  mount_uploader :image, AboutUploader

  validates :image, presence: true

  belongs_to :about

  def show
    image
  end
end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  enum type_alternative:  %w(accessibility usability)
  has_and_belongs_to_many :questions

  validates :description, :weight, presence: true

  def name
    description
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :description, presence: true
  has_many :questions

  def name
      description
  end

  def self.include_category
    category = Category.order(:id)
    category.includes(:questions).order(:id)
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :phone, :message, :subject, presence: true
end

app/models/device.rb
class Device < ActiveRecord::Base
  include SearchCop
  mount_uploader :phone_img, CellImageUploader

  belongs_to :mark
  has_many :evaluations
  validates :phone_img, :model_device, :processor, :os, :size_device, :type_device, :mark, presence:true

  # Implementation search with gem searchcop
  search_scope :search do
    attributes :model_device, :processor, :os, :type_device
  end


  def cont_eval
    evaluations.count
  end

  # def self.search(search)
  #   where("model_device like ?", "%#{search}%")
  # end


  def percent_of_evaluation(eval_spec)
    percent = 0
    percent = (eval_spec * 100 / cont_eval)
    percent > 0 ? percent.to_s << "%" :percent
  end


end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base
  enum type_diagnostic:  %w(accessibility usability)


  validates :description, :score, presence: true


  def self.result (s, t)
    result = where('score <= ?', s).where('type_diagnostic = ?', t).first
    result.try(:description)
  end

  def self.count (s, t)
    result = where('score <= ?', s).where('type_diagnostic = ?', t).count
    result.try(:description)
  end

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :device
  belongs_to :user
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  has_many :devices
  validates :name, presence: true

  end

app/models/question.rb
class Question < ActiveRecord::Base

  enum type_question:  %w(accessibility usability)

  belongs_to :category
  belongs_to :quiz

  has_and_belongs_to_many :alternatives

  def name
    enunciation
  end

  def self.include_category
    category = Category.order(:id)
    category.includes(:questions).order(:id)
  end
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  has_many :questions
end

app/models/slide.rb
class Slide < ApplicationRecord
  mount_uploader :image, SlideUploader
  validates :title, :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :evaluations

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def evaluation
    render layout: false
  end

  def index
    if params[:search]
      @device = Device.search(params[:search])
    else
      @device = Device.all.order :id
    end
  end

  def show
    @device =  Device.find params[:id]
  end

end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/report_helper.rb
module ReportHelper

  def search_score_diagnostic
    @sim = Diagnostic.find_by(name: 'Sim')
  end



  def search_score_diagnostic_acessibilidade
    @sim = Diagnostic.find_by(name: 'Sim')
    @nao = Diagnostic.find_by(name: 'Não')
  end


  def eval_spec(device, dg)
   @evals_yes =  Evaluation.where("device_id = ?", device).where("score_acessibilidade = ? ", dg.first.score).count
   @evals_no =  Evaluation.where("device_id = ?", device).where("score_acessibilidade = ? ", dg.last.score).count

  end



  def percent_of_votes
    percent = 0
    percent = (votes * 100 / poll_question.votes) if votes.size > 0 && poll_question.votes > 0
    percent > 0 ? percent.to_s << "%" :percent
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/reports/evaluation.html.erb
<%= stylesheet_link_tag  'report', media: 'print' %>
<h1 class="titulo-pdf">Relatório do Aparelho</h1>

app/views/reports/index.erb
<link href="../../assets/stylesheets/simple-sidebar.css" rel="stylesheet">
<div id="wrapper">
  <%= render 'layouts/menu' %>

  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">

          <% if current_user.present? %>
            <h1 id ="texto-titulo">Seleção de Dispositivos</h1>
          <%else%>
            <h1 id ="texto-titulo">Seleção de Dispositivos</h1>
          <% end %>

          <div id="box-search" class="clearfix">
            <%= render 'layouts/device/search' %>
          </div>

          <%if @device.present?%>

          <% @device.each do |device| %>
            <div id="divPBaixo"class="coluna-4 clearfix">
              <div id="image-device">
               <%= image_tag device.phone_img_url(:thumb)%>
              </div>
              <p id="name-device" class="centraliza"><%= device.model_device%> </p>
              <%= link_to "Gerar Relatório", report_path(device), class: "btn btn-primary"  %>
            </div>
          <%end%>

          <%else%>
            <div id="para-error">
              <p id="trapezio-descendente">Desculpe-me porém, não foi encontrado nada com este nome: " <%= params[:search]%>". </p>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<link href="../../assets/stylesheets/simple-sidebar.css" rel="stylesheet">
<div id="wrapper">
  <%= render 'layouts/includes/menu' %>

  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">

          <% if current_user.present? %>
            <h1 id ="texto-titulo">Seleção de Dispositivos</h1>
          <%else%>
            <h1 id ="texto-titulo">Seleção de Dispositivos</h1>
          <% end %>

          <div id="box-search" class="clearfix">
            <%= render 'layouts/device/search' %>
          </div>

          <%if @device.present?%>

          <% @device.each do |device| %>
            <div id="divPBaixo"class="coluna-4 clearfix">
              <div id="image-device">
               <%= image_tag device.phone_img_url(:thumb)%>
              </div>
              <p id="name-device" class="centraliza"><%= device.model_device%> </p>
              <%= link_to "Gerar Relatório", report_path(device), class: "btn btn-primary"  %>
            </div>
          <%end%>

          <%else%>
            <div id="para-error">
              <p id="trapezio-descendente">Desculpe-me porém, não foi encontrado nada com este nome: " <%= params[:search]%>". </p>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/show.erb
<link href="../../assets/stylesheets/simple-sidebar.css" rel="stylesheet">
<div id="wrapper">
  <%= render 'layouts/menu' %>

  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <% if current_user.present? %>
          <h1 id ="texto-titulo" class="centraliza">Relatório </h1>
          <% end %>
          <div id="divPBaixo"class="coluna-4 clearfix">
            <div id="image-device">
              <%= image_tag @device.phone_img_url(:thumb) %>
            </div>
            <div class="container-ficha-tecnica">
              <p id="name-device" class="centraliza"><%= @device.model_device%> </p>
              <p id="name-device" class="centraliza"><%= @device.mark.name%> </p>
              <p id="name-device" class="centraliza"><%= @device.processor%> </p>
              <p id="name-device" class="centraliza"><%= @device.os%> </p>
              <p id="name-device" class="centraliza"><%= @device.size_device%> </p>
              <p id="name-device" class="centraliza"><%= @device.type_device%> </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<link href="../../assets/stylesheets/simple-sidebar.css" rel="stylesheet">

<% test  = search_score_diagnostic_acessibilidade %>
<% total = eval_spec(@device, test) %>
<div id="wrapper">
  <%= render 'layouts/includes/menu' %>

  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <% if current_user.present? %>
          <h1 id ="texto-titulo" class="centraliza">Relatório </h1>
          <% end %>
          <div id="divPBaixo"class="coluna-4 clearfix">
            <div id="image-device">
              <%= image_tag @device.phone_img_url(:thumb) %>
            </div>
            <div class="container-ficha-tecnica">
              <p id="name-device" class="centraliza"><%= @device.model_device%> </p>
              <p id="name-device" class="centraliza"><%= @device.mark.name%> </p>
              <p id="name-device" class="centraliza"><%= @device.processor%> </p>
              <p id="name-device" class="centraliza"><%= @device.os%> </p>
              <p id="name-device" class="centraliza"><%= @device.size_device%> </p>
              <p id="name-device" class="centraliza"><%= @device.type_device%> </p>
            </div>

            <div class="poll">
            <h1 class="aside__title"> Pontuação Acessibilidade </h1>
              <p class="poll__info">
                Esse dispositivo obteve <strong><%= @device.cont_eval %> avaliações</strong>

            <ol class="poll__list">
                <li class="poll__answer">
                <span class="poll__label" for=""><%= test.name %></span>
                <div class="poll__percentage" style="min-width: <%= @device.percent_of_evaluation(total) %>;"><%= @device.percent_of_evaluation(total)%></div>
              </li>
              <li class="poll__answer">
              <span class="poll__label" for=""><%= test.name %></span>
              <div class="poll__percentage" style="min-width: <%= @device.percent_of_evaluation(total) %>;"><%= @device.percent_of_evaluation(total)%></div>
            </li>
            </ol>

            <div class="poll">
            <h1 class="aside__title"> Pontuação Usabilidade </h1>
              <p class="poll__info">
                Esse dispositivo obteve <strong><%= @device.cont_eval %> avaliações</strong>

            <ol class="poll__list">
                <li class="poll__answer">
                <span class="poll__label" for=""><%= test.name %></span>
                <div class="poll__percentage" style="min-width: <%= @device.percent_of_evaluation(total) %>;"><%= @device.percent_of_evaluation(total)%></div>
              </li>
              <li class="poll__answer">
              <span class="poll__label" for=""><%= test.name %></span>
              <div class="poll__percentage" style="min-width: <%= @device.percent_of_evaluation(total) %>;"><%= @device.percent_of_evaluation(total)%></div>
            </li>
            </ol>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>